from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from agents.base import BaseAgent
from integrations import GitHubClient, IntegrationError
from message_bus import AgentMessage


class EngineerAgent(BaseAgent):
    def __init__(self, *, github: GitHubClient, **kwargs) -> None:
        super().__init__(**kwargs)
        self.github = github

    def _startup_name(self, product_spec: dict[str, Any]) -> str:
        persona = product_spec.get("personas", [{}])[0].get("name", "Launch")
        first_feature = product_spec.get("features", [{}])[0].get("name", "Mind")
        feature_word = re.findall(r"[A-Za-z]+", first_feature)
        name = f"{persona}{feature_word[0] if feature_word else 'Mind'}"
        return name[:24] or "LaunchMind"

    def _fallback_html(self, product_spec: dict[str, Any]) -> str:
        startup_name = self._startup_name(product_spec)
        features = "\n".join(
            f"<li><strong>{feature['name']}</strong> - {feature['description']}</li>"
            for feature in product_spec["features"]
        )
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{startup_name}</title>
  <style>
    :root {{
      --bg: #f4efe6;
      --ink: #1f2937;
      --accent: #c84c22;
      --card: #fffaf2;
    }}
    body {{
      margin: 0;
      font-family: Georgia, 'Times New Roman', serif;
      background: radial-gradient(circle at top, #fff8ec, var(--bg));
      color: var(--ink);
    }}
    .wrap {{
      max-width: 980px;
      margin: 0 auto;
      padding: 72px 24px;
    }}
    .hero, .panel {{
      background: rgba(255, 250, 242, 0.92);
      border: 1px solid rgba(31, 41, 55, 0.08);
      border-radius: 24px;
      padding: 32px;
      box-shadow: 0 20px 60px rgba(31, 41, 55, 0.08);
    }}
    h1 {{
      font-size: clamp(2.5rem, 6vw, 4.5rem);
      line-height: 0.95;
      margin-bottom: 12px;
    }}
    .subheadline {{
      font-size: 1.15rem;
      max-width: 700px;
      margin-bottom: 24px;
    }}
    .cta {{
      display: inline-block;
      padding: 14px 24px;
      background: var(--accent);
      color: white;
      border-radius: 999px;
      text-decoration: none;
      font-weight: bold;
    }}
    ul {{
      padding-left: 20px;
      line-height: 1.7;
    }}
    .panel {{
      margin-top: 24px;
    }}
  </style>
</head>
<body>
  <main class="wrap">
    <section class="hero">
      <p>Built by LaunchMind agents</p>
      <h1>{startup_name}</h1>
      <p class="subheadline">{product_spec['value_proposition']}</p>
      <a class="cta" href="#waitlist">Join the waitlist</a>
    </section>
    <section class="panel">
      <h2>Why users care</h2>
      <ul>
        {features}
      </ul>
    </section>
  </main>
</body>
</html>
"""

    def _generate_html(self, product_spec: dict[str, Any], feedback: str | None) -> str:
        system_prompt = "You are a frontend engineer. Return only a complete HTML document with embedded CSS."
        user_prompt = (
            f"Build a landing page for this product spec:\n{json.dumps(product_spec, indent=2)}\n"
            f"Revision feedback: {feedback or 'None'}\n"
            "Requirements: headline, subheadline, features section, CTA button, polished basic CSS, mobile-friendly."
        )
        return self.llm.complete_text(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            fallback=lambda: self._fallback_html(product_spec),
        )

    def _fallback_issue_body(self, product_spec: dict[str, Any]) -> str:
        lines = ["## Goal", product_spec["value_proposition"], "", "## Priority Features"]
        lines.extend(f"- {feature['name']}: {feature['description']}" for feature in product_spec["features"])
        return "\n".join(lines)

    def handle_message(self, message: AgentMessage) -> None:
        if message.message_type not in {"task", "revision_request"}:
            return

        product_spec = message.payload["product_spec"]
        feedback = message.payload.get("feedback")
        html = self._generate_html(product_spec, feedback)

        html_path = self.output_dir / "index.html"
        html_path.write_text(html, encoding="utf-8")

        startup_name = self._startup_name(product_spec)
        branch = f"agent-{startup_name.lower()}-landing-page"
        issue_title = "Initial landing page"
        issue_body = self._fallback_issue_body(product_spec)
        pr_title = f"Initial landing page for {startup_name}"
        pr_body = (
            f"## Summary\n- Add an initial landing page for {startup_name}\n"
            f"- Reflect the product value proposition and top features\n"
            f"- Generated by the Engineer agent\n"
        )

        issue_url = "dry-run://github/issues/initial-landing-page"
        pr_url = "dry-run://github/pulls/initial-landing-page"
        commit_sha = "dry-run-commit"
        dry_run = True

        if self.github.enabled:
            try:
                self.github.create_branch(branch)
                issue = self.github.find_issue_by_title(issue_title)
                if issue is None:
                    issue = self.github.create_issue(issue_title, issue_body)
                commit = self.github.upsert_file(
                    path="index.html",
                    content=html,
                    branch=branch,
                    message="Add initial landing page",
                    author_name="EngineerAgent",
                    author_email="agent@launchmind.ai",
                )
                pr = self.github.find_pull_request(branch)
                if pr is None:
                    pr = self.github.create_pull_request(pr_title, pr_body, branch)
                issue_url = issue["html_url"]
                pr_url = pr["html_url"]
                commit_sha = commit["commit"]["sha"]
                dry_run = False
            except IntegrationError as exc:
                self.log("GitHub integration failed, continuing in dry-run mode.", {"error": str(exc)})

        self.send_message(
            to_agent="ceo",
            message_type="result",
            payload={
                "html_path": str(html_path),
                "html_content": html,
                "branch": branch,
                "issue_url": issue_url,
                "pr_url": pr_url,
                "commit_sha": commit_sha,
                "dry_run": dry_run,
            },
            parent_message_id=message.message_id,
        )
